### ISSUE TITLE
Issue with pots

### ISSUE THREAD

**Issue by muzs1** [dalemyers/libmonzo#3]
Hi, before I start I would just like to say I have very limited programming knowledge but I would like to use this for a small project.
I have done some testing with this but run into some issues.
The first one is that the pots part doesn’t work below is the current code.

def pots(self) -> List[Pot]:
        """Return the list of pots the user has."""
        self.log.debug("Requesting pots.")
        response = self.get('pots')
        return Pot.from_json(response.json())

Here is what I change to make it work

def pots(self, *, account_id: str) -> List[Pot]:
        """Return the list of pots the user has."""
        self.log.debug("Requesting pots.")
        response = self.get(f'pots?current_account_id={account_id}')
        return Pot.from_json(response.json())

It looks like Monzo now require an account_id to list the pots.

For the project I would like to do, I need to use the API as “Confidential” so I am issues a "refresh_token", I have worked out how to get the refresh token added to the “client” but have no idea how to go about refreshing the access.

**Comment by dalemyers** [comment]
This library was only ever really used for a small personal project, so it's really out of date now. 

I'm happy to accept any PRs though (but won't really be able to test).

**Comment by muzs1** [comment]
Okay don't worry, thanks for the reply.
I will see if I can pick out the bits I need and make it do what I need.
